blank_issues_enabled: false
contact_links:
  - name: "💬 Support: Discussions"
    url: https://github.com/udecode/zustand-x/discussions
    about: Share ideas, ask and answer questions in our Discussions.